package nhotstuff

import (
	"diablo-benchmark/core/configs"
	"diablo-benchmark/core/results"
	"diablo-benchmark/core/workload"
)

// Controller implements the blockchain.Controller interface for native HotStuff.
type Controller struct{}

// Init initializes the Controller.
func (c *Controller) Init(chainConfig *configs.ChainConfig, benchConfig *configs.BenchConfig, t []int) error {
	return nil
}

// Setup sets up the blockchain state as needed by the benchmark.
func (c *Controller) Setup() error {
	return nil
}

// Generate generates the benchmark workload.
func (c *Controller) Generate() (*workload.Workload, error) {
	return nil, nil
}

// Worker implements the blockchain.Worker interface for native HotStuff.
type Worker struct{}

// Init initializes the Worker.
func (w *Worker) Init(chainConfig *configs.ChainConfig) error {
	return nil
}

// ParseWorkload parses the workload generated by Controller.Generate.
func (w *Worker) ParseWorkload(workload [][]byte) error {
	return nil
}

// StartBenchmark does everything needed when the benchmark starts.
func (w *Worker) StartBenchmark() error {
	return nil
}

// SendTransaction sends the transaction parsed during ParseWorkload.
func (w *Worker) SendTransaction(index int) error {
	return nil
}

// StopBenchmark does everything needed when the benchmark stops.
func (w *Worker) StopBenchmark() error {
	return nil
}

// Generate generates the results collected during the benchmark.
func (w *Worker) Generate() *results.EventLog {
	return nil
}
